using Printf

# 1. Define the 39 atoms of the Nafion chain (Element, X, Y, Z)
# This represents a short Nafion segment (backbone + side chain)
polymer_atoms = [
    # Backbone carbons and fluorines
    ("C",  0.00,  0.00,  0.00), ("F",  0.00,  1.09,  0.50), ("F",  0.00, -1.09,  0.50),
    ("C",  1.54,  0.00,  0.00), ("F",  1.54,  1.09, -0.50), ("F",  1.54, -1.09, -0.50),
    ("C",  3.08,  0.00,  0.00), ("F",  3.08,  1.09,  0.50), ("F",  3.08, -1.09,  0.50),
    ("C",  4.62,  0.00,  0.00), ("F",  4.62,  1.09, -0.50), ("F",  4.62, -1.09, -0.50),
    ("C",  6.16,  0.00,  0.00), ("F",  6.16,  1.09,  0.50), ("F",  6.16, -1.09,  0.50),
    ("C",  7.70,  0.00,  0.00), ("F",  7.70,  1.09, -0.50), ("F",  7.70, -1.09, -0.50),
    ("C",  9.24,  0.00,  0.00), ("F",  9.24,  1.09,  0.50), ("F",  9.24, -1.09,  0.50),
    ("C", 10.78,  0.00,  0.00), ("F", 10.78,  1.09, -0.50), ("F", 10.78, -1.09, -0.50),
    # Side chain ether linkage (-O-CF2-CF(CF3)-O-CF2-CF2-SO3H)
    ("O",  3.08,  0.00, -1.40),
    ("C",  3.08,  1.20, -2.10), ("F",  2.00,  1.20, -2.60), ("F",  4.16,  1.20, -2.60),
    ("C",  3.08,  2.40, -1.20), ("C",  1.80,  2.40, -0.40), ("F",  1.80,  3.40,  0.40),
    ("F",  0.80,  2.40, -1.20), ("F",  1.80,  1.40,  0.40), ("O",  4.20,  2.40, -0.40),
    ("C",  4.20,  3.60,  0.40), ("F",  3.12,  3.60,  1.10), ("F",  5.28,  3.60,  1.10),
    ("C",  4.20,  4.80, -0.50), ("F",  3.12,  4.80, -1.20), ("F",  5.28,  4.80, -1.20),
    ("S",  4.20,  6.30,  0.50), ("O",  3.00,  6.30,  1.30), ("O",  5.40,  6.30,  1.30),
    ("O",  4.20,  7.40, -0.50), ("H",  4.20,  8.20,  0.00)
]

# 2. Define Explicit Molecular Bonds (Type, Atom1_Index, Atom2_Index)
bond_mappings = [
    ("cc", 1, 4), ("cc", 4, 7), ("cc", 7, 10), ("cc", 10, 13), ("cc", 13, 16), ("cc", 16, 19), ("cc", 19, 22),
    ("cf", 1, 2), ("cf", 1, 3), ("cf", 4, 5), ("cf", 4, 6), ("cf", 7, 8), ("cf", 7, 9),
    ("cf", 10, 11), ("cf", 10, 12), ("cf", 13, 14), ("cf", 13, 15), ("cf", 16, 17), ("cf", 16, 18),
    ("cf", 19, 20), ("cf", 19, 21), ("cf", 22, 23), ("cf", 22, 24),
    ("co", 7, 25), ("oc", 25, 26), ("cf", 26, 27), ("cf", 26, 28), ("cc", 26, 29),
    ("cc", 29, 30), ("cf", 30, 31), ("cf", 30, 32), ("cf", 30, 33), ("co", 29, 34),
    ("oc", 34, 35), ("cf", 35, 36), ("cf", 35, 37), ("cc", 35, 38), ("cf", 38, 39),
    ("cf", 38, 40), ("cs", 38, 41), ("so", 41, 42), ("so", 41, 43), ("so", 41, 44), ("oh", 44, 45)
]

# Atom types and typical partial charges
type_map = Dict("C" => ("@atom:C", -0.20), "F" => ("@atom:F", -0.20), "O" => ("@atom:O", -0.40), "S" => ("@atom:S", 1.00), "H" => ("@atom:H", 0.40))

# Write the Packmol coordinate input (.xyz)
open("nafion_chain.xyz", "w") do io
    println(io, length(polymer_atoms))
    println(io, "Nafion chain generated by Julia")
    for (idx, a) in enumerate(polymer_atoms)
        @printf(io, "%-2s %12.6f %12.6f %12.6f\n", a[1], a[2], a[3], a[4])
    end
end

# Write the Moltemplate layout input (.lt)
open("nafion.lt", "w") do io
    println(io, "NafionChain {")
    println(io, "  write_once(\"Data Masses\") {")
    println(io, "    @atom:C  12.011\n    @atom:F  18.998\n    @atom:O  15.999\n    @atom:S  32.060\n    @atom:H   1.008")
    println(io, "  }\n")
    
    println(io, "  write(\"Data Atoms\") {")
    for (idx, a) in enumerate(polymer_atoms)
        element = a[1]
        atom_type, charge = type_map[element]
        @printf(io, "    \$atom:%s%d  \$mol:.  %s  %6.2f  %12.6f  %12.6f  %12.6f\n", lowercase(element), idx, atom_type, charge, a[2], a[3], a[4])
    end
    println(io, "  }\n")

    println(io, "  write(\"Data Bonds\") {")
    for (b_idx, bond) in enumerate(bond_mappings)
        b_type, a1_idx, a2_idx = bond
        if a1_idx <= length(polymer_atoms) && a2_idx <= length(polymer_atoms)
            a1_elem = lowercase(polymer_atoms[a1_idx][1])
            a2_elem = lowercase(polymer_atoms[a2_idx][1])
            @printf(io, "    \$bond:b%d  @bond:%s  \$atom:%s%d  \$atom:%s%d\n", b_idx, b_type, a1_elem, a1_idx, a2_elem, a2_idx)
        end
    end
    println(io, "  }\n}")
end

println("Successfully generated nafion_chain.xyz and nafion.lt!")