import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ==========================================
# 1. LOAD THE DATA
# ==========================================
# Read the file generated by your LAMMPS run.in (skip the first title line)
data = pd.read_csv("water_velocity.dat", sep=r"\s+", skiprows=1, 
                   names=["Step", "Avg_Vx", "Avg_Vy", "Avg_Vz"])

# Convert steps to time (Assuming timestep 1.0 fs)
data["Time_ps"] = data["Step"] * 1.0 / 1000.0 

# ==========================================
# 2. FIND THE STABILIZATION POINT
# ==========================================
# In a short run, let's look at the last 50% of the data where it has equilibrated
equilibration_start_row = int(len(data) * 0.5)
stable_data = data.iloc[equilibration_start_row:]

# Calculate the average Drift Velocity (vd) in the X direction
# LAMMPS real units: Angstroms / femtosecond (A/fs)
vd_A_fs = stable_data["Avg_Vx"].mean()

# Convert Angstroms/fs to meters/second (m/s) for standard physics SI units
vd_m_s = vd_A_fs * 1e5  

print(f"--- Simulation Analysis ---")
print(f"Average Drift Velocity (vd): {vd_A_fs:.6f} A/fs ({vd_m_s:.2f} m/s)")

# ==========================================
# 3. CALCULATE PROTON CONDUCTIVITY
# ==========================================
# Set up your constant properties (Adjust these to match your exact packmol box layout!)
E_field = 0.1* 1e10         # 0.1 V/Angstrom converted to Volts/meter (V/m)
box_length_m = 86 * 1e-10  # Example box length of 50 Angstroms converted to meters
box_volume = box_length_m**3 

num_waters = 6000             # Change this to exact number of water particles
q_proton = 1.602e-19         # Elementary charge of a proton in Coulombs

# Number Density (rho) = number of charge carriers per unit volume
rho = num_waters / box_volume

# Current Density (J) = rho * q * vd
J = rho * q_proton * vd_m_s

# Conductivity (sigma) = J / E
# Output unit: Siemens per meter (S/m)
# abs to get positi
conductivity = abs(J / E_field)

print(f"Calculated Proton Conductivity: {conductivity:.4f} S/m")

# ==========================================
# 4. PLOT THE GRAPH TO VISUALLY CHECK STABILITY
# ==========================================
plt.figure(figsize=(8, 5))
plt.plot(data["Time_ps"], data["Avg_Vx"], label="Measured Velocity ($V_x$)", color="blue")
plt.axhline(y=vd_A_fs, color="red", linestyle="--", label=f"Stable Avg = {vd_A_fs:.4f} A/fs")

plt.title("Water Flow Drift Velocity Over Time")
plt.xlabel("Time (ps)")
plt.ylabel("Drift Velocity $V_x$ (A/fs)")
plt.grid(True)
plt.legend()
plt.savefig("velocity_stabilization.png")
print("Graph saved as 'velocity_stabilization.png'")