import numpy as np
import matplotlib.pyplot as plt

# 1. Load the data generated by LAMMPS (skipping the header line)
data = np.loadtxt('water_msd.dat', skiprows=1)
steps = data[:, 0]
msd = data[:, 1]

# Convert timesteps to time in picoseconds (1 step = 1 femtosecond = 0.001 ps)
time_ps = steps * 0.001

# 2. Calculate the Diffusion Coefficient (D)
# Formula: D = slope / 6. Using linear regression (polyfit) to find the slope.
slope, intercept = np.polyfit(time_ps, msd, 1)
D = slope / 6.0  # Units: Å²/ps

print("-" * 50)
print(f"Calculated Water Diffusion Coefficient (D): {D:.4f} Å²/ps")
print("-" * 50)

# 3. Generate the Graph Plot
plt.figure(figsize=(8, 5))
plt.plot(time_ps, msd, 'o-', color='dodgerblue', label='LAMMPS Data')
plt.plot(time_ps, slope * time_ps + intercept, '--', color='crimson', label=f'Linear Fit (D = {D:.3f} Å²/ps)')

plt.title('Water Mean Squared Displacement (MSD) vs Time', fontsize=12, fontweight='bold')
plt.xlabel('Time (ps)', fontsize=10)
plt.ylabel('MSD ($Å^2$)', fontsize=10)
plt.grid(True, linestyle=':', alpha=0.6)
plt.legend()

# Save the plot as an image in your directory
plt.savefig('diffusion_plot.png', dpi=300)
print("Graph successfully saved as 'diffusion_plot.png'!")