import numpy as np
import matplotlib.pyplot as plt

# 1. Load the data table generated by LAMMPS (skipping the header line)
data = np.loadtxt('volume_swelling.dat', skiprows=1)
steps = data[:, 0]
volume = data[:, 1]

# Convert timesteps to time in picoseconds (1 step = 1 femtosecond = 0.001 ps)
time_ps = steps * 0.001

# 2. Calculate the Swelling Percentage
# Initial volume is the first row, final volume is the last row
v_initial = volume[0]
v_final = volume[-1]

# Percentage formula: ((V_final - V_initial) / V_initial) * 100
swelling_percentage = ((v_final - v_initial) / v_initial) * 100

print("-" * 50)
print(f"Starting Box Volume: {v_initial:.2f} Å³")
print(f"Final Stable Volume: {v_final:.2f} Å³")
print(f"Calculated Membrane Swelling: {swelling_percentage:.2f}%")
print("-" * 50)

# 3. Create the Swelling Graph Plot
plt.figure(figsize=(8, 5))
plt.plot(time_ps, volume, '-', color='forestgreen', linewidth=2, label='Box Volume ($Å^3$)')

# Add a horizontal indicator line for the initial vs final volume
plt.axhline(y=v_initial, color='gray', linestyle=':', label=f'Initial ({v_initial:.0f} $Å^3$)')
plt.axhline(y=v_final, color='darkorange', linestyle='--', label=f'Final ({v_final:.0f} $Å^3$)')

plt.title('Nafion Membrane Volume Swelling vs Time', fontsize=12, fontweight='bold')
plt.xlabel('Time (ps)', fontsize=10)
plt.ylabel('Simulation Box Volume ($Å^3$)', fontsize=10)
plt.grid(True, linestyle=':', alpha=0.6)
plt.legend()

# Save the plot as an image file
plt.savefig('swelling_plot.png', dpi=300)
print("Graph successfully saved as 'swelling_plot.png'!")